spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://postgres:5432/coopcredit_db}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}

  jpa:
    show-sql: false

logging:
  level:
    root: WARN
    com.coopcredit: INFO