spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://postgres:5432/coopcredit_db}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none  # Let Flyway handle schema management

  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    root: WARN
    com.coopcredit: INFO

# Risk Central Service
risk-central:
  url: ${RISK_CENTRAL_URL:http://risk-central:8081}